lib/taskTracker_web/router.ex
defmodule TaskTrackerWeb.Router do
  use TaskTrackerWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :get_current_user
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
    plug :fetch_session
    plug :get_current_user
    plug :fetch_flash
  end

  # a method that sets the current_user
  def get_current_user(conn, _params) do
    user_id = get_session(conn, :user_id)

    if user_id do
      user = TaskTracker.Accounts.get_user!(user_id)
      assign(conn, :current_user, user)
    else
      assign(conn, :current_user, nil)
    end
  end

  scope "/", TaskTrackerWeb do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index
    get "/feed", PageController, :feed
    resources "/users", UserController
    resources "/tasks", TaskController
    post "/session", SessionController, :create
    delete "/session", SessionController, :delete
  end

  # Other scopes may use custom stacks.
  scope "/api/v1", TaskTrackerWeb do
    pipe_through :api
    resources "/blocks", BlockController, except: [:new, :edit]
  end
end

lib/taskTracker_web/views/layout_view.ex
defmodule TaskTrackerWeb.LayoutView do
  use TaskTrackerWeb, :view
end

lib/taskTracker_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Hello TaskTracker!</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
  </head>

  <body class="alice-blue">
    <div class="container">
      <nav class="navbar navbar-toggleable-md navbar-light bg-faded">
        <h1 class="navbar-brand mb-0">TaskTracker</h1>
        <%= if @current_user do %>
          <%= link "my tasks", to: page_path(@conn, :feed), class: "nav-item nav-link" %>
          <%= link "my profile", to: user_path(@conn, :edit, @current_user.id), class: "nav-item nav-link" %>
          <%= link "subordinate tasks", to: task_path(@conn, :index), class: "nav-item nav-link" %>
          <%= link "user profiles", to: user_path(@conn, :index), class: "nav-item nav-link" %>
          <%= link "log out", to: "/session", method: :delete, class: "nav-item nav-link" %>
          <%= @current_user.name %>
        <% end %>
      </nav>

      <%= if get_flash(@conn, :info) do %>
        <p class="alert alert-info text-center border-0" role="alert">
          <%= get_flash(@conn, :info) %>
        </p>
      <% end %>
      <%= if get_flash(@conn, :error) do %>
        <p class="alert alert-danger text-center border-0" role="alert">
          <%= get_flash(@conn, :error) %>
        </p>
      <% end %>
      <main role="main">
        <%= render @view_module, @view_template, assigns %>
      </main>

    </div> <!-- /container -->
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>